services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:latest
    container_name: app-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    container_name: app-db
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
