services:
  ex1:
    build: .
    volumes:
      - ./src/r01_sanityCheck:/app
    working_dir: /app
    command: cargo run

  ex2:
    build: .
    volumes:
      - ./src/r02_helloGalaxy:/app
    working_dir: /app
    command: cargo run

  ex3:
    build: .
    volumes:
      - ./src/r03_flagItAllOut:/app
    working_dir: /app
    command: cargo run