#define no_cap    1
#define cap       0
#define be        ==
#define rn        ;
#define chief     main
#define no        !
#define sussin    ?
#define bussin    :
#define yikes     break;
#define deadass   void
#define vibin     --
#define ongod     ++
#define fr        long
#define bouta     &
#define finna     =
#define tho       {
#define gyatt     }
#define rizzler   int
#define lowkey    return
#define skibidi   -1.2f
#define sigma     char
#define ohio      *
#define fanum     printf